language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
notifications:
  slack: hr46:zi9kNkElRi7scpZXZL7DHNXy
after_success:
- chmod 600 .travis/deploy_key
- mv .travis/deploy_key ~/.ssh/id_rsa
- git remote add deploy ssh://ec2-user@54.213.203.244/home/ec2-user/repo/
- git push deploy
before_install:
- openssl aes-256-cbc -K $encrypted_f700efe58037_key -iv $encrypted_f700efe58037_iv
  -in deploy_key.enc -out .travis/deploy_key -d
